sudo: required
services:
    - docker 

before_install:
    - docker build -t react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true react-test npm run test -- --coverage

after_success:
    - docker build -t rahul1916/multi-client ./client
    - docker build -t rahul1916/multi-nginx ./nginx
    - docker build -t rahul1916/multi-server ./server
    - docker build -t rahul1916/multi-worker ./worker
    # log in to docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin  
    # push images to docker hub
    - docker push rahul1916/multi-client
    - docker push rahul1916/multi-nginx
    - docker push rahul1916/multi-server
    - docker push rahul1916/multi-worker

deploy:
    provider: elasticbeanstalk
    region: us-east-2
    app: multi-docker
    env: MultiDocker-env-1
    bucket_name: elasticbeanstalk-us-east-2-066361185434
    bucket_path: multi-docker
    on: 
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY